# This file was generated by GoReleaser. DO NOT EDIT.
cask "xytz" do
  version "0.9.1-demo"

  on_macos do
    on_intel do
      sha256 "965b7b5771df5399c91edad25d2a88830d25a8ffc1568144cfdc131aac6642d8"
      url "https://github.com/xdagiz/xytz/releases/download/v#{version}/xytz-v#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "883b6e28afd528233eadc55355bc42604a832648909b3bc1684241425c5c6a3d"
      url "https://github.com/xdagiz/xytz/releases/download/v#{version}/xytz-v#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0272f67496c2a23c28c7dc55a8c4323a222f0f4b26e7c4200bf4beb5274610b9"
      url "https://github.com/xdagiz/xytz/releases/download/v#{version}/xytz-v#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "96d1785085e1b34bda3f57f3fdf86dd5664bee120880141d284ba3eced67ef1c"
      url "https://github.com/xdagiz/xytz/releases/download/v#{version}/xytz-v#{version}-linux-arm64.tar.gz"
    end
  end

  name "xytz"
  desc "a beautiful TUI YouTube Downloader"
  homepage "https://github.com/xdagiz/xytz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xytz"

  # No zap stanza required

end
