# This file was generated by GoReleaser. DO NOT EDIT.
cask "xytz" do
  version "0.9.2"

  on_macos do
    on_intel do
      sha256 "5a9fac12bd10c5901d2f1af6e5e88dc41bb844d04f28646ebb832cbc359c8dcc"
      url "https://github.com/xdagiz/xytz/releases/download/v#{version}/xytz-v#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "43217d15da3b2cd41839a9c3f8a105e6bdd08ecead6a151a3b21af220f1442af"
      url "https://github.com/xdagiz/xytz/releases/download/v#{version}/xytz-v#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8fbde7bb5dae1577d67233f39686b0bd5992567aac0766fbc1f235f17cc9d212"
      url "https://github.com/xdagiz/xytz/releases/download/v#{version}/xytz-v#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "5c8ca8231d313550b0c03605bbfe421077fa769f678b0015f3f26a6aaa8cf856"
      url "https://github.com/xdagiz/xytz/releases/download/v#{version}/xytz-v#{version}-linux-arm64.tar.gz"
    end
  end

  name "xytz"
  desc "a beautiful TUI YouTube Downloader"
  homepage "https://github.com/xdagiz/xytz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xytz"

  # No zap stanza required

end
